services:
  qa:
    image: eclipse-temurin:25-jre
    environment:
      - POST
      - DATABASE_URL
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
    ports:
      - 127.0.0.1:8530:8530
    entrypoint: >
      sh -c "java --enable-native-access=ALL-UNNAMED -jar qa.jar"

  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql
      - ./dumps:/dumps

volumes:
  m2:
    external: true
  data:
    driver: local
