services:
  qa:
    image: eclipse-temurin:25-jre
    env_file: ".env"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 127.0.0.1:8530:8530
    entrypoint: >
      sh -c "java --enable-native-access=ALL-UNNAMED -jar qa.jar"

  db:
    image: postgres:18
    env_file: ".env"
    volumes:
      - data:/var/lib/postgresql
      - ./dumps:/dumps

volumes:
  data:
